<?php
$a='';
$a=$a."<table border=\"1\">\n"; 
$a=$a."<tbody>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td colspan=\"3\" rowspan=\"1\"><img src=\"images/logo.png\" alt=\"Logo\" width=\"125\" height=\"45\" /></td>\n"; 
$a=$a."<td colspan=\"2\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Input Zero Technologies Pvt. Ltd.</td>\n"; 
$a=$a."<td colspan=\"4\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td colspan=\"5\" align=\"center\"><strong>Employee Salary slip</strong></td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Employee ID</td>\n"; 
$a=$a."<td>$empid</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>Month</td>\n"; 
$a=$a."<td>$mon</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Salary slip for the month of</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td colspan=\"5\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Name</td>\n"; 
$a=$a."<td>$name</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>No of Days</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Employee</td>\n"; 
$a=$a."<td>$emp</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>Actual</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Date Of Joining</td>\n"; 
$a=$a."<td>$doj</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>PF/Acc No</td>\n"; 
$a=$a."<td>$pf</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>No of Days in Quarter</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>PAN No</td>\n"; 
$a=$a."<td>$pan</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>Actual</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td colspan=\"\&quot;5\&quot;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td colspan=\"3\"><strong>Gross Earnings</strong></td>\n"; 
$a=$a."<td colspan=\"2\"><strong>Deductions</strong></td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Salary Head</td>\n"; 
$a=$a."<td>Monthly</td>\n"; 
$a=$a."<td>Earned</td>\n"; 
$a=$a."<td>Head</td>\n"; 
$a=$a."<td>Amount</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Basic</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$mbasic</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$basic</td>\n"; 
$a=$a."<td>Income Tax</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$itax</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>HRA</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$mhra</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$hra</td>\n"; 
$a=$a."<td>PF</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$pfded</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Special Allowance</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$mspecial_allowance</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$special_allowance</td>\n"; 
$a=$a."<td>ESI</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$esi</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Conveyance</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$mconv</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$conv</td>\n"; 
$a=$a."<td>Professional Tax</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$ptax</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Child Education</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$mchild</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$child</td>\n"; 
$a=$a."<td>Labour Welfare Fund</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$lwf</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>On Call Allowance</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$oca</td>\n"; 
$a=$a."<td>Arrears</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$aded</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Night Shift Allowance</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$nsa</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Medical Reimbursement</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$med</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Laptop Allowance</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$lap</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>PLIB</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$plib</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Arrear Income</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$arr_inc</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Others</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td colspan=\"2\">Total</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$mgross</td>\n"; 
$a=$a."<td>Total</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$ded</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td colspan=\"4\"><strong>Net Earnings</strong></td>\n"; 
$a=$a."<td style=\"text-align: right;\">$netsal</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td colspan=\"5\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td style=\"text-align: center;\" colspan=\"2\"><strong>Tax Calculation</strong></td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: center;\" colspan=\"2\"><strong>Exemptions</strong></td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Yearly Projection</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;$yproj</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>HRA Exemption</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;$hra_ex</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>Conveyance</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$conv_ex</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Taxable salary</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;$taxable_inc</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>80C Savings</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$ann_80c</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Net Tax</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;$ntax</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>80D Exemption</td>\n"; 
$a=$a."<td style=\"text-align: right;\">$ann_80d</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Surcharge@10%</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>80G Exemption</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Cess@3%</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>Interest on House Loan</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Total Yearly Tax</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;$ntax</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>Tax per month</td>\n"; 
$a=$a."<td style=\"text-align: right;\">&nbsp;$itax</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."</tbody>\n"; 
$a=$a."</table>\n";
?>