<?php
echo "&nbsp";
//echo "<input class=\"btn btn-warning\" id=\"btn\" type=\"button\" name=\"print_sal\" value=\"Print\" onclick=\"goToURL()\">";


$a='';
$a=$a."<page>"."<table border=\"1\" id=\"sal_table\">\n";

$a=$a."<tbody>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" colspan=\"3\" rowspan=\"1\"><img src=\"images/logo.png\" alt=\"Logo\" width=\"125\" height=\"45\" /></td>\n"; 
$a=$a."<td border=\"0\" colspan=\"2\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\">Input Zero Technologies Pvt. Ltd.</td>\n"; 
$a=$a."<td border=\"0\" colspan=\"4\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" colspan=\"5\" align=\"center\"><strong>Employee Salary slip</strong></td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr border=\"0\">\n"; 
$a=$a."<td border=\"0\">Employee ID</td>\n"; 
$a=$a."<td border=\"0\">$empid</td>\n"; 
$a=$a."<td border=\"0\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\">Month</td>\n"; 
$a=$a."<td border=\"0\">$mon</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\">Salary slip for the month of</td>\n"; 
$a=$a."<td border=\"0\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
//$a=$a."<tr>\n"; 
//$a=$a."<td colspan=\"5\">&nbsp;</td>\n"; 
//$a=$a."</tr>\n"; 
//$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\">Name</td>\n"; 
$a=$a."<td border=\"0\">$name</td>\n"; 
$a=$a."<td border=\"0\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\">No of Days</td>\n"; 
$a=$a."<td border=\"0\">$days</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr border=\"0\">\n"; 
$a=$a."<td border=\"0\">Employee</td>\n"; 
$a=$a."<td border=\"0\">$emp</td>\n"; 
$a=$a."<td border=\"0\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\">Actual</td>\n"; 
$a=$a."<td border=\"0\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\">Date Of Joining</td>\n"; 
$a=$a."<td border=\"0\">$doj</td>\n"; 
$a=$a."<td border=\"0\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\">PF/Acc No</td>\n"; 
$a=$a."<td border=\"0\">$pf</td>\n"; 
$a=$a."<td border=\"0\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\">No of Days in Quarter</td>\n"; 
$a=$a."<td border=\"0\">$emp_days_quater</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\">PAN No</td>\n"; 
$a=$a."<td border=\"0\">$pan</td>\n"; 
$a=$a."<td border=\"0\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\">Actual</td>\n";
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
//$a=$a."<tr>\n"; 
//$a=$a."<td colspan=\"\&quot;5\&quot;\">&nbsp;</td>\n"; 
//$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\"  colspan=\"3\"><strong>Gross Earnings</strong></td>\n"; 
$a=$a."<td border=\"0\"  colspan=\"2\"><strong>Deductions</strong></td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Salary Head</td>\n"; 
$a=$a."<td border=\"0\" >Monthly</td>\n"; 
$a=$a."<td border=\"0\" >Earned</td>\n"; 
$a=$a."<td border=\"0\" >Head</td>\n"; 
$a=$a."<td border=\"0\" >Amount</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Basic</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$mbasic</td>\n"; 
$a=$a."<td border=\"0\" style=\"text-align: right;\">$basic</td>\n"; 
$a=$a."<td border=\"0\" >Income Tax</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$itax</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >HRA</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$mhra</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$hra</td>\n"; 
$a=$a."<td border=\"0\" >PF</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$pfded</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Special Allowance</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$mspecial_allowance</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$special_allowance</td>\n"; 
$a=$a."<td border=\"0\" >ESI</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$esi</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Conveyance</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$mconv</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$conv</td>\n"; 
$a=$a."<td border=\"0\" >Professional Tax</td>\n"; 
$a=$a."<td border=\"0\" style=\"text-align: right;\">$ptax</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Child Education</td>\n"; 
$a=$a."<td  border=\"0\" style=\"text-align: right;\">$mchild</td>\n"; 
$a=$a."<td  border=\"0\" style=\"text-align: right;\">$child</td>\n"; 
$a=$a."<td border=\"0\" >Labour Welfare Fund</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$lwf</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >On Call Allowance</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td  border=\"0\" style=\"text-align: right;\">$oca</td>\n"; 
$a=$a."<td border=\"0\" >Arrears</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$aded</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Night Shift Allowance</td>\n"; 
$a=$a."<td  border=\"0\" style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$nsa</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Medical Reimbursement</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$med</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td  border=\"0\" style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Laptop Allowance</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >PLIB</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td  border=\"0\" style=\"text-align: right;\">$plib</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td  border=\"0\" style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Arrear Income</td>\n"; 
$a=$a."<td  border=\"0\" style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$arr_inc</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Others</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\"  colspan=\"2\">Total</td>\n"; 
$a=$a."<td  border=\"0\" style=\"text-align: right;\">$mgross</td>\n"; 
$a=$a."<td border=\"0\" >Total</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$ded</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\"  colspan=\"4\"><strong>Net Earnings</strong></td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$netsal</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\"  colspan=\"5\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: center;\" colspan=\"2\"><strong>Tax Calculation</strong></td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: center;\" colspan=\"2\"><strong>Exemptions</strong></td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Yearly Projection</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;$yproj</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >HRA Exemption</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;$hra_ex</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >Conveyance</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$conv_ex</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Taxable salary</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;$taxable_inc</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >80C Savings</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$ann_80c</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr border=\"0\" >\n"; 
$a=$a."<td border=\"0\" >Net Tax</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;$ntax</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >80D Exemption</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">$ann_80d</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Surcharge@10%</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >80G Exemption</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Cess@3%</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >Interest on House Loan</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Total Yearly Tax</td>\n"; 
$a=$a."<td  border=\"0\" style=\"text-align: right;\">&nbsp;$ntax</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
$a=$a."<tr>\n"; 
$a=$a."<td border=\"0\" >Tax per month</td>\n"; 
$a=$a."<td border=\"0\"  style=\"text-align: right;\">&nbsp;$itax</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."<td border=\"0\" >&nbsp;</td>\n"; 
$a=$a."</tr>\n"; 
/*$a=$a."<tr>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."<td>&nbsp;</td>\n"; 
$a=$a."</tr>\n"; */
$a=$a."</tbody>\n"; 
$a=$a."</table>\n"."</page>";

echo $a;



?>