<?php
echo "<table border=\"1\">\n"; 
echo "<tbody>\n"; 
echo "<tr>\n"; 
echo "<td colspan=\"3\" rowspan=\"1\"><img src=\"images/logo.png\" alt=\"Logo\" width=\"125\" height=\"45\" /></td>\n"; 
echo "<td colspan=\"2\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Input Zero Technologies Pvt. Ltd.</td>\n"; 
echo "<td colspan=\"4\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td colspan=\"5\" align=\"center\"><strong>Employee Salary slip</strong></td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Employee ID</td>\n"; 
echo "<td>$empid</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>Month</td>\n"; 
echo "<td>$mon</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Salary slip for the month of</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td colspan=\"5\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Name</td>\n"; 
echo "<td>$name</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>No of Days</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Employee</td>\n"; 
echo "<td>$emp</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>Actual</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Date Of Joining</td>\n"; 
echo "<td>$doj</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>PF/Acc No</td>\n"; 
echo "<td>$pf</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>No of Days in Quarter</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>PAN No</td>\n"; 
echo "<td>$pan</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>Actual</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td colspan=\"\&quot;5\&quot;\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td colspan=\"3\"><strong>Gross Earnings</strong></td>\n"; 
echo "<td colspan=\"2\"><strong>Deductions</strong></td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Salary Head</td>\n"; 
echo "<td>Monthly</td>\n"; 
echo "<td>Earned</td>\n"; 
echo "<td>Head</td>\n"; 
echo "<td>Amount</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Basic</td>\n"; 
echo "<td style=\"text-align: right;\">$mbasic</td>\n"; 
echo "<td style=\"text-align: right;\">$basic</td>\n"; 
echo "<td>Income Tax</td>\n"; 
echo "<td style=\"text-align: right;\">$itax</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>HRA</td>\n"; 
echo "<td style=\"text-align: right;\">$mhra</td>\n"; 
echo "<td style=\"text-align: right;\">$hra</td>\n"; 
echo "<td>PF</td>\n"; 
echo "<td style=\"text-align: right;\">$pfded</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Special Allowance</td>\n"; 
echo "<td style=\"text-align: right;\">$mspecial_allowance</td>\n"; 
echo "<td style=\"text-align: right;\">$special_allowance</td>\n"; 
echo "<td>ESI</td>\n"; 
echo "<td style=\"text-align: right;\">$esi</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Conveyance</td>\n"; 
echo "<td style=\"text-align: right;\">$mconv</td>\n"; 
echo "<td style=\"text-align: right;\">$conv</td>\n"; 
echo "<td>Professional Tax</td>\n"; 
echo "<td style=\"text-align: right;\">$ptax</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Child Education</td>\n"; 
echo "<td style=\"text-align: right;\">$mchild</td>\n"; 
echo "<td style=\"text-align: right;\">$child</td>\n"; 
echo "<td>Labour Welfare Fund</td>\n"; 
echo "<td style=\"text-align: right;\">$lwf</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>On Call Allowance</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">$oca</td>\n"; 
echo "<td>Arrears</td>\n"; 
echo "<td style=\"text-align: right;\">$aded</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Night Shift Allowance</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">$nsa</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Medical Reimbursement</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">$med</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Laptop Allowance</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">$lap</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>PLIB</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">$plib</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Arrear Income</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">$arr_inc</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Others</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td colspan=\"2\">Total</td>\n"; 
echo "<td style=\"text-align: right;\">$mgross</td>\n"; 
echo "<td>Total</td>\n"; 
echo "<td style=\"text-align: right;\">$ded</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td colspan=\"4\"><strong>Net Earnings</strong></td>\n"; 
echo "<td style=\"text-align: right;\">$netsal</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td colspan=\"5\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td style=\"text-align: center;\" colspan=\"2\"><strong>Tax Calculation</strong></td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td style=\"text-align: center;\" colspan=\"2\"><strong>Exemptions</strong></td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Yearly Projection</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;$yproj</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>HRA Exemption</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;$hra_ex</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>Conveyance</td>\n"; 
echo "<td style=\"text-align: right;\">$conv_ex</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Taxable salary</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;$taxable_inc</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>80C Savings</td>\n"; 
echo "<td style=\"text-align: right;\">$ann_80c</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Net Tax</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;$ntax</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>80D Exemption</td>\n"; 
echo "<td style=\"text-align: right;\">$ann_80d</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Surcharge@10%</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>80G Exemption</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Cess@3%</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>Interest on House Loan</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Total Yearly Tax</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;$ntax</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>Tax per month</td>\n"; 
echo "<td style=\"text-align: right;\">&nbsp;$itax</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "<td>&nbsp;</td>\n"; 
echo "</tr>\n"; 
echo "</tbody>\n"; 
echo "</table>\n";
?>